apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  MP3_QUEUE: "mp3_convert"
  VIDEO_QUEUE: "video_upload"
  SMTP_SERVER: "smtp.sendgrid.net"
  SMTP_PORT: "587"
  SMTP_USERNAME: "y"
  SMTP_PASSWORD: "SG.zNo3op4YS7SbmyrTB5u_I7H7w"
  FROM_EMAIL: "norepi"


